server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: online_drug_sales
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/odsm?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
mybatis:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
